//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesMain
    {
        public int ID_SQL { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string id { get; set; }
        public string localisation { get; set; }
        public string notes { get; set; }
        public string title { get; set; }
        public string uid { get; set; }
    }
}
